// Types for ./examples-catalog.json, which is generated by `npm run generate-examples` and
// gitignored. Without this, `tsc` fails in any checkout where that script has not run yet,
// because examples-catalog.ts imports the file. TypeScript reads the types from here
// (enabled by `allowArbitraryExtensions` in tsconfig.json); bundlers and Jest still load the
// real JSON at build and test time.
import { ExamplesWithConfig } from "../types";

declare const examplesCatalog: ExamplesWithConfig[];
export default examplesCatalog;
