name: Issue Triage

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  triage:
    permissions:
      issues: write
    uses: aws/aws-durable-execution-ci/.github/workflows/issue-triage.yml@4c98745db4fad4ba2176b2dcf40d6af3a8a39b78
